### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by UnknownUntilNow**
should fix https://github.com/n76/Local-GSM-Backend/issues/47

### CODE REVIEW

**Comment by agilob** [comment]
http://chris.beams.io/posts/git-commit/

**Comment by UnknownUntilNow** [comment]
I don't know how I can rename the commit (after pushing to GitHub).

**Comment by agilob** [comment]
https://stackoverflow.com/questions/11603473/how-do-you-rename-a-git-commit-pushed-to-github#11603609

**Comment by UnknownUntilNow** [comment]
already reverted the old commit and created a new one

**Pull request closed without merging**
