### PR TITLE
Support requesting OpenCellID key automatically

### PR DESCRIPTION
**Pull request by agilob**
+ code refactoring
+ one more label
+ see changes in commit messages and code!
screenshot_2015-06-29-20-16-56

### CODE REVIEW

**Comment by agilob** [comment]
I had to increase android api version, see commit message:

most methods realted to TelephonyManger require A-API 17 or 18 otherwise an exception is thrown
exception is not visible because whole block of code is in {}catch(Excetpion) block, service wouldn't work and it wouldn't crash

commit increases required API so TelephonyManager will work as supposed.

**Comment by n76** [comment]
Lots of formatting changes which get in the way of looking for the functional changes. . . Would be nice to submit the formatting clean up as a separate commit.

Opening the preferences and tapping on "OpenCellIP API" to manually set a value results in a crash for me. Sorry, did not capture the stack trace. Once "Request new OpenCellID key" is pressed it seems to work okay.

Started download and build of new database and after only a little while got a crash in the lookup area. Here is the trace:

    E/AndroidRuntime(13526): java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
    E/AndroidRuntime(13526): 	at org.fitchfamily.android.gsmlocation.GSMService$1$1.sameLoc(GSMService.java:59)
    E/AndroidRuntime(13526): 	at org.fitchfamily.android.gsmlocation.GSMService$1$1.doIt(GSMService.java:77)
    E/AndroidRuntime(13526): 	at org.fitchfamily.android.gsmlocation.GSMService$1$1.onCellLocationChanged(GSMService.java:92)
    E/AndroidRuntime(13526): 	at android.telephony.PhoneStateListener$1.handleMessage(PhoneStateListener.java:290)
    E/AndroidRuntime(13526): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    E/AndroidRuntime(13526): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime(13526): 	at org.fitchfamily.android.gsmlocation.GSMService$1.run(GSMService.java:105)

**Comment by agilob** [comment]
>Opening the preferences and tapping on "OpenCellIP API" to manually set a value results in a crash for me

Just spent 15minutes and I can't reproduce it. In that part of code I added only `final` keyword and it should not cause crash. If you could get stacktrace would be great, I'll fix it then.
```
-        EditTextPreference ociKeyPreference = (EditTextPreference) this.findPreference("oci_key_preference");
+        final EditTextPreference ociKeyPreference = (EditTextPreference) this.findPreference("oci_key_preference");
```

Last two commits introduce new features, I had to read that code before ;) I think we will benefit from it in the future, you had mixed formatting styles tabs vs. spaces / K&R vs java. If you take a look at `      public void genDatabase(boolean useOCI, boolean useMLS, String OciKey, ` - it didn't do anything because of wrong variables used in putExtra methods :D

**Comment by n76** [comment]
Okay, that seems to have fixed the crash. I think the unexpected quit I had when I first attempted to set a API key was simply in the other thread.

Yeah, the code was a bit of a mess... A couple of different editors with different settings on expand tabs or not, etc. So the clean up is welcome, I just find it easier if clean up and either bug fixes or new functionality are in different comments.

**Comment by n76** [comment]
Looks like the NPE fix (restore check for first parameter null) seems to fix the issues I had.

Code was a mess, thanks for the clean up. But I much prefer to have clean up and functionality commits separate. :)

**Comment by agilob** [comment]
I fixed it anyway ;_; 

If you want you can merge those two commits two, they add the same key validation as automatic mode has, additionally I added one more check for NPE in that code. It shouldn't crash even when user changes their mind and press back.

**Comment by n76** [comment]
Backed out some of the last key validation as it rejects my OCID API key which starts with 'bfa9b9fb-' instead of 'dev-'. :)

Other than that, I've merged your changes and pushed a new version back to github.

Thank you for your contribution!

**Comment by agilob** [comment]
Acordding to examples in their API all keys start with dev-usr-- I don't know what that `usr--` part is. In AndroidIMSICatcherDetector we check for `dev-` too and it works fine. Key validator is based on my assumption that all API keys have `dev-` part.

**Comment by n76** [comment]
Maybe they have changed things around but the key I've had for quite a while is of the form xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx where each 'x' is a hex character/digit. And that key worked as recently as 8 hours ago when I was checking things.

Or maybe they have one format key given out from the interface you've coded and a different one from http://opencellid.org/#action=database.requestForApiKey where the user needs to specify an email and create a password.

**Pull request merged**
